zookeeper:
  image: rancher/zookeeper:3.4.8
  environment:
    ZK_ENSEMBLE_SIZE: ${ZK_ENSEMBLE_SIZE}
    ZK_TICK_TIME: ${ZK_TICK_TIME}
    ZK_INIT_LIMIT: ${ZK_INIT_LIMIT}
    ZK_SYNC_LIMIT: ${ZK_SYNC_LIMIT}
    ZK_MAX_CLIENT_CXNS: ${ZK_MAX_CLIENT_CXNS}
    JVMFLAGS: "-Xms${ZK_HEAP_SIZE}m -Xmx${ZK_HEAP_SIZE}m"
  labels:
    io.rancher.sidekicks: data
  volumes_from:
  - data
data:
  image: rancher/zookeeper:3.4.8
  entrypoint: /bin/true
  labels:
    io.rancher.container.start_once: 'true'
  net: none
  volumes:
  - /data