logspout:
  restart: always
  environment:
    ROUTE_URIS: 'logstash://logstash:5000'
    LOGSPOUT: 'ignore'
  volumes:
  - '/var/run/docker.sock:/var/run/docker.sock'
  external_links:
  - logs/logstash-collector:logstash
  labels:
    io.rancher.scheduler.global: 'true'
  tty: true
  image: cloudnautique/logspout-logstash:v0.1.0
  stdin_open: true
